[merra2_aerosols]
git-tree-sha1 = "6018165de4d718628fafc86a01721a155faa4cb0"

[ozone_concentrations]
git-tree-sha1 = "235a16e02c24a28b20244c0f2e7f149cc783166f"

[era5_cloud]
git-tree-sha1 = "8bad412ada94be95a2e11c794b499c49d746be50"

[era5_hourly_atmos_raw]
git-tree-sha1 = "8234def2ead82e385a330a48ed2f0c030e434065"

[era5_hourly_atmos_processed]
git-tree-sha1 = "a1a465e8d237d78bef1e6d346054da395787a9f9"

[cfsite_gcm_forcing]
git-tree-sha1 = "2f196bcac8950f8cb79ead41821f423d092b8951"
lazy = true

    [[cfsite_gcm_forcing.download]]
    sha256 = "78f13efcbc71350609c8a73ed66ff28fe3653fb7a0274e34b52d720651c1c2ec"
    url = "https://caltech.box.com/shared/static/elv5ksf3av3kum9552jxhnmlgu7vxr8u.nc"

[merra2_aerosols_lowres]
git-tree-sha1 = "1efc90e4955112c3ac9c3c522d6232b770c0f53b"

    [[merra2_aerosols_lowres.download]]
    sha256 = "ce7df957f950c13db6dcdec4dd09b33631606a98f47eba22d1c29ff0c913be53"
    url = "https://caltech.box.com/shared/static/c152v3f03l0w745qv7d8td9eguz9glsy.gz"

[ozone_concentrations_lowres]
git-tree-sha1 = "6693f8451b447543952b3d557d733c7e5c670ed3"

    [[ozone_concentrations_lowres.download]]
    sha256 = "908384b32e90c733c2173654afbb974d238a9a516ad8965039077c6ddb29b5f0"
    url = "https://caltech.box.com/shared/static/6c16wt7i1htxq6tadpt1ng2uftjgdtpr.gz"

[earth_orography_30arcseconds]
git-tree-sha1 = "03dd08fcbf363ed055a176dd7adefb60ff1c3493"

[earth_orography_60arcseconds]
git-tree-sha1 = "fe19d8dbe7a18ff39588e1f718014b0479d9c0f7"
lazy = true

    [[earth_orography_60arcseconds.download]]
    sha256 = "eca66c0701d1c2b9e271742314915ffbf4a0fae92709df611c323f38e019966e"
    url = "https://caltech.box.com/shared/static/4asrxcgl6xsgenfcug9p0wkkyhtqilgk.gz"

[co2_dataset]
git-tree-sha1 = "9c3bd05b68e820fceb43d130ce6b4e86ce788e4e"

    [[co2_dataset.download]]
    sha256 = "46923ec3e1f9028a11899c47e6b13d675d84daa9db2f37351a19ec9187f87865"
    url = "https://caltech.box.com/shared/static/fuwajscgyblccy8y9aq01d0pgy91gwut.gz"

[era5_cloud_lowres]
git-tree-sha1 = "258a2626b6008bf2f926b2711f8cb5273edc3916"

    [[era5_cloud_lowres.download]]
    sha256 = "c1d29e996fcdc0c263f8b54ca1ddd858c46326fc4cfc3ab3dc71e5e598322de8"
    url = "https://caltech.box.com/shared/static/lr9k1s2pgeqzli8goxq9y2liiy3u6kni.gz"

[topo_drag]
git-tree-sha1 = "9970989c13c2ad015ab5738d42fd9f5b320f1451"

    [[topo_drag.download]]
    sha256 = "2960d7ee10b3a15203dfa8b05b1b94c9546212230e5828787577864113829d6e"
    url = "https://caltech.box.com/shared/static/pflpi9qoay7jknmajlj1uaxqtnp4frj2.gz"

[DYAMOND_SUMMER_ICS_p98deg]
git-tree-sha1 = "46aa28a9177dd7e4cbb813eeba3e02597c3ba071"
lazy = true

    [[DYAMOND_SUMMER_ICS_p98deg.download]]
    sha256 = "9a5efd20d68d9b954af2fd7803bccdda3fc7ef4ff60421ed13d18f768312d2e3"
    url = "https://caltech.box.com/shared/static/whn01xr83v0s4p8tc59ds3nvfsfe6ebs.gz"

[DYAMOND_SUMMER_ICS_p14deg]
git-tree-sha1 = "789c8dd160b022a6c714a102c1495530c7a9d20c"

[weather_model_ic]
git-tree-sha1 = "1c05bc305e79ceaab8c537be4f8c4a26465996a3"

[era5_inst_model_levels]
git-tree-sha1 = "8aae2d7330f90a029a4891be658a691e4e3362dc"

[cloud_fraction_nn]
git-tree-sha1 = "c2412372bdf40ba73f496dc0fe427d063e31533b"

    [[cloud_fraction_nn.download]]
    sha256 = "a0b8b682539d975c1cc331549d0222a0eda121f5b2977cc63486368a7dc07885"
    url = "https://caltech.box.com/shared/static/vdb6r7cv5tj6uhrphn5a4352smsxdqgs.gz"

[ogwd_computed_drag_h6]
git-tree-sha1 = "bf189454e5cb19962d8324e7e1667b7aa867bff9"
lazy = true

    [[ogwd_computed_drag_h6.download]]
    sha256 = "a54c3ab3c0213e7c6d11fa73ab5fe54f3799e8383c6c3164e98d9c257945a4ef"
    url = "https://caltech.box.com/shared/static/hrupvak4oceoi2camqey166u61421q25.gz"

[ogwd_computed_drag_h8]
git-tree-sha1 = "df178b2f3efba5c9670c7f75cd04637f844a8145"
lazy = true

    [[ogwd_computed_drag_h8.download]]
    sha256 = "8375fd84c2b2b3ef9b333666702c55687f130e299753f4e21e0fd99f04fa355d"
    url = "https://caltech.box.com/shared/static/bmzj3r7b2lez3xjggymi2ifoq5vg6jnq.gz"

[ogwd_computed_drag_h12]
git-tree-sha1 = "2aa7ab2ca8b562aa8ba92905bd664cc64a976ad2"
lazy = true

    [[ogwd_computed_drag_h12.download]]
    sha256 = "8b3834b9e3ed93bf08c6b7a0bbec83ff418ce357f186f67fc441b0e8d288ae32"
    url = "https://caltech.box.com/shared/static/p058wvdd42zhidgt3copgn88ijgs2c3a.gz"

[ogwd_computed_drag_h16]
git-tree-sha1 = "158138fc38c3aa08ce1605ac65ff1983a1a407db"
lazy = true

    [[ogwd_computed_drag_h16.download]]
    sha256 = "af9987bf9bf63899014b99b9420536cdd06f7bc05ea44b37f31e42e3b7840ed7"
    url = "https://caltech.box.com/shared/static/imtr9k7ktzm0fff1k32zphb8oybmrsvn.gz"

[ogw_computed_drag_h30]
git-tree-sha1 = "ab898b33fcde4a719ee12cb1271399177d6a3561"

    [[ogw_computed_drag_h30.download]]
    sha256 = "9d5b7d5046911069f4c6917dc01b0c88ca2bb1273f203d45f92577ab2b83442b"
    url = "https://caltech.box.com/shared/static/7ut92ej4qs15pm1g6vpykvmpqw6cjztj.gz"
    
[ogw_computed_drag_h60]
git-tree-sha1 = "d11b75df5be566eae42d6a3f2b3f60a381feacf8"

    [[ogw_computed_drag_h60.download]]
    sha256 = "6bcccb58ff3e3687deb8782234a2518a4b92ce00a1b0f830f4c84d19f9384585"
    url = "https://caltech.box.com/shared/static/0e5l0qvuf06zmj7gl625yb4vlt7phknz.gz"
