status = [
  "ci 1.6.0 - ubuntu-latest",
  "ci 1.6.0 - windows-latest",
  "ci 1.6.0 - macOS-latest",
  "docbuild",
  "format",
]
delete_merged_branches = true
timeout_sec = 10800
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
