status = [
  # "ci 1.9.0 - ubuntu-latest",
  # "ci 1.9.0 - windows-latest",
  # "ci 1.9.0 - macos-latest",
  "buildkite/climaatmos-ci",
  "docbuild",
  "format",
]
delete_merged_branches = true
timeout_sec = 72000
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
