[precipitation_timescale]
value = 600

[entr_inv_tau]
value = 0.002

[entr_coeff]
value = 0

[detr_inv_tau]
value = 0

[detr_vertdiv_coeff]
value = 0.6

[detr_buoy_coeff]
value = 0.12

[min_area_limiter_scale]
value = 0

[max_area_limiter_scale]
value = 0

[Tq_correlation_coefficient]
value = 0.6
