[zd_rayleigh]
value = 40000.0

[zd_viscous]
value = 40000.0

[entr_inv_tau]
value = 0.001

[entr_coeff]
value = 0

[detr_inv_tau]
value = 0

[detr_buoy_coeff]
value = 0.12

[detr_vertdiv_coeff]
value = 0

[min_area_limiter_scale]
value = 0

[max_area_limiter_scale]
value = 0

#[condensation_evaporation_timescale]
#value = 100

#[sublimation_deposition_timescale]
#value = 100

