[zd_rayleigh]
value = 40000.0

[min_area_limiter_scale]
value = 0

[zd_viscous]
value = 40000.0

[mixing_length_tke_surf_flux_coeff]
value = 0.3331950998157493

[max_area_limiter_scale]
value = 0

[mixing_length_diss_coeff]
value = 0.04640288100600733

[entr_param_vec]
value = [-45.97815905276861, -20.29437694493032, -22.269204417686513, 3.470895262420817, 0.8421581647335002, -0.8534958362066539]

[EDMF_surface_area]
value = 0.06399178163606391

[mixing_length_eddy_viscosity_coefficient]
value = 0.5892594727125273

[alpha_rayleigh_w]
value = 10.0

[pressure_normalmode_drag_coeff]
value = 0.22685176632582243

#[mixing_length_Prandtl_number_0]
#value = 2.909243754318121

[entr_mult_limiter_coeff]
value = 0.4641383877134538

[entr_inv_tau]
#value = 0.008362201402729065
value = 0.024

[mixing_length_static_stab_coeff]
value = 0.29736273245468714

[pressure_normalmode_buoy_coeff1]
value = 0.024795188237279258

[mixing_length_Prandtl_maximum]
value = 4.2

[precipitation_timescale]
value = 600

[detr_inv_tau]
value = 0

[detr_vertdiv_coeff]
value = 0

[detr_buoy_coeff]
value = 0.12
