[zd_rayleigh]
value = 35000.0

[alpha_rayleigh_uh]
alias = "alpha_rayleigh_uh"
value = 0.0

[precipitation_timescale]
value = 600

[entr_inv_tau]
value = 0.002

[entr_coeff]
value = 0

[detr_inv_tau]
value = 0

[detr_buoy_coeff]
value = 0.12

[detr_vertdiv_coeff]
value = 0

[min_area_limiter_scale]
value = 0

[max_area_limiter_scale]
value = 0
