[EDMF_surface_area]
value = 0.1

[EDMF_min_area]
value = 1.0e-5

[EDMF_max_area]
value = 0.7

[entr_inv_tau]
value = 0.0001

[entr_coeff]
value = 0.3

[min_area_limiter_scale]
value = 0

[detr_inv_tau]
value = 0

[detr_coeff]
value = 0

[detr_buoy_coeff]
value = 0

[detr_vertdiv_coeff]
value = 0

[detr_massflux_vertdiv_coeff]
value = 1

[max_area_limiter_scale]
value = 0

[pressure_normalmode_drag_coeff]
value = 40.0

[cloud_fraction_param_vec]
value = [-0.8682884598195689, -0.33516903962740846, 0.7670039058300598, 1.4290562302093883, -0.9954849517708659, -0.4372110416889669, 0.6527811691350767, -0.49334645225903695, 1.2371306591958426, 0.0841798844472313, 4.159101610121286, -4.23858354116815, -4.153737619746136, -3.5951161893914825, 1.905681074479979, -3.1282191766402163, 0.7592199812892576, 0.5618582685015713, -0.08134081829212864, 0.10733658559373292, -0.12655738125289695, 0.1785476350073567, -0.7461399706631531, -1.5577865139897704, 0.1279148272819999, 0.25049469576518, -0.7980938050252959, 2.90496071978161, 0.9936047854718992, -0.2858689975220472, 2.8794032466434887, -3.170333262616446, 0.3507499050311194, -0.12466887445926417, -0.1452411798794418, 0.17372933916058367, -0.08754525598052403, 0.07042495369331678, 0.038950828602612994, 0.17704085348577908, -0.46165498801236265, 0.08953215254663223, 0.5210803208385826, 0.2541370232953319, -0.7972800051826472, 0.1384430780149269, -0.2155895902063, -0.7550122730888524, -0.610289216969961, 0.2592132127678255, 0.4550045307660597, -0.2373961923692655, -0.5811247959607664, 0.489616885303196, 0.3169312409286337, -0.39387779104180864, 1.5709323512987567, 0.4804024660882293, -0.6019870444485985, -0.376652938598611, 0.4473571232974799, 0.1934710678257229, -0.8932571958359236, -1.7172936064750248, -0.29059610931965457, 0.4713338713195026, 1.4257980598336142, 0.7991583802449825, 1.6605848267289642, -0.6642369874338104, 1.359892648501992, 1.0900900243728275, -1.1515309104019762, -0.34789096125835933, 0.8178059348415846, 0.7087608970512826, 1.0533252031320948, -0.8364386816192027, 1.4781568154831253, 0.26170253881793043, -1.588066004770028, -0.9088307659295064, 0.8423653609508381, 0.8051130771090592, 1.0758811855205128, -0.47092941513865666, 0.24307725170843006, 1.3408713657082527, 0.9372211242244086, 0.746745272172156, -0.826479025166701, -0.2005176100786385, -0.8823666526276142, -0.2867709049516592, -1.7949470866113597, -1.5194005623328983, -2.1572459946348657, 0.5688883826761171, -0.702884575658961, -0.8000741369080921, -0.27548375557694627, -4.364583499390056, 0.8067121360473769, 0.9740852021006478, 0.47362234638194467, 0.06632122172276392, -0.1440277817850779, -0.3497590170310852, 0.19068162229536328, 0.4390048212924756, 0.028856521832984927, -0.478525938352815, -1.797853294938206, -1.2777946840848708, 0.6336664957984173, 0.4349747000278921, 1.2334342684753938, -1.5266704055897058, 2.202292088441342, 1.317270449962564, -0.16122488419451264]
type = "float"
