[EDMF_surface_area]
value = 0.1

[EDMF_min_area]
value = 1.0e-5

[EDMF_max_area]
value = 0.7

[entr_inv_tau]
value = 0.0001

[entr_coeff]
value = 0.3

[turb_entr_param_vec]
value = [1e-10, 0.0, 0.0]

[min_area_limiter_scale]
value = 0

[detr_inv_tau]
value = 0

[detr_coeff]
value = 0

[detr_buoy_coeff]
value = 0

[detr_vertdiv_coeff]
value = 0

[detr_massflux_vertdiv_coeff]
value = 1

[max_area_limiter_scale]
value = 0

[pressure_normalmode_drag_coeff]
value = 40.0

[gcmdriven_momentum_relaxation_timescale]
value = 21600.0

[gcmdriven_scalar_relaxation_timescale]
value = 86400.0

[gcmdriven_relaxation_minimum_height]
value = 3000.0

[gcmdriven_relaxation_maximum_height]
value = 3500.0

[zd_rayleigh]
value = 20000.0

[mixing_length_param_vec]
value = [0.08152589946985245, -9.220643997192383, 1.456505298614502, 4.150567838223651e-05, 1.2203592632431537e-05, 0.1851629614830017, -56.88902282714844, -7.018703460693359]