[EDMF_max_area]
value = 0.7

[min_area_limiter_scale]
value = 0

[detr_inv_tau]
value = 0

[detr_coeff]
value = 0

[detr_buoy_coeff]
value = 0

[detr_vertdiv_coeff]
value = 0

[max_area_limiter_scale]
value = 0

[EDMF_min_area]
value = 1.0e-5

[zd_rayleigh]
value = 20000.0

[mixing_length_tke_surf_scale]
value = 5.6101216504240545
type = "float"

[mixing_length_diss_coeff]
value = 0.3739697514813775
type = "float"

[diagnostic_covariance_coeff]
value = 1.4362168064049219
type = "float"

[entr_inv_tau]
value = 0
type = "float"

[entr_param_vec]
value = [-1.2633841186916668, -0.4599815783034937, -0.46293146485015296, 1.4203614863252911, 0.5642481281364011, 0.32604896101664416, -0.09664796099945236, 0.7220191192213364, 0.16903223715665835, 3.2461705926260187, -1.028004360914299, 0.3402928311687101]
type = "float"

[EDMF_surface_area]
value = 0.0723478159897135
type = "float"

[mixing_length_eddy_viscosity_coefficient]
value = 0.05607209843375782
type = "float"

[turb_entr_param_vec]
value = [0.08116105272535512, 6497.824633456959]
type = "float"

[pressure_normalmode_drag_coeff]
value = 36.11459646731416
type = "float"

[mixing_length_Prandtl_number_0]
value = 0.8133326091843176
type = "float"

[mixing_length_static_stab_coeff]
value = 0.8242481923752288
type = "float"

[pressure_normalmode_buoy_coeff1]
value = 0.06277435215676228
type = "float"

[cloud_fraction_param_vec]
value = [-0.74087787, -0.3999826, 0.74106497, 1.1249413, -0.7692651, -0.3288731, 1.1838305, -0.44306874, 1.2400066, 0.08220636, 4.162183, -4.255733, -4.1470923, -3.5917249, 1.9350492, -3.1265073, 0.62557614, 0.59036386, 0.38260913, -0.04336004, -0.022237444, 0.21320705, -0.73384005, -1.5728604, 0.12632804, 0.25012466, -0.79051197, 2.901747, 0.99446714, -0.28530046, 2.8799458, -3.1699934, -0.008281425, 0.04032145, 0.0022431544, 0.23048602, 0.002109726, -0.0027990476, 0.014690841, 0.015412016, -0.47020674, 0.0911798, 0.5514113, 0.26639637, -0.7011554, 0.048635133, -0.11820925, -0.74253386, -0.6299769, 0.25821522, 0.45762223, -0.24785824, -0.54129744, 0.43782854, 0.32382002, -0.37370422, 1.6636233, 0.42479172, -0.60597306, -0.22591783, 0.34605289, 0.20129378, -0.9169212, -1.7097968, -0.15992814, 0.42109442, 1.4578766, 0.96085256, 1.4828439, -0.71255374, 1.3403219, 1.1625379, -1.1571414, -0.34768724, 0.82053113, 0.6995275, 1.0853457, -0.8751673, 1.4938492, 0.26861444, -1.5908451, -0.90890837, 0.8357902, 0.7919029, 1.0858604, -0.4867975, 0.23034543, 1.3411491, 1.1225301, 0.6950453, -0.81695104, -0.023932422, -1.0674969, -0.29764092, -1.7934479, -1.5139523, -2.155796, 0.56899023, -0.7082227, -0.80488247, -0.28393012, -4.3622384, 0.790751, 0.97193205, 0.14509517, -0.1046927, -0.13245293, -0.17821075, 0.11578787, 0.26055467, -0.31904995, -0.19141985, -1.5523665, -0.5322224, 0.7271137, 0.63075674, 1.1851735, -1.550133, 2.073769, 1.3312619, -0.09809579]
type = "float"
