[EDMF_max_area]
value = 0.7

[min_area_limiter_scale]
value = 0

[detr_inv_tau]
value = 0

[detr_coeff]
value = 0

[detr_buoy_coeff]
value = 0

[detr_vertdiv_coeff]
value = 0

[max_area_limiter_scale]
value = 0

[EDMF_min_area]
value = 1.0e-5

[zd_rayleigh]
value = 20000.0

[mixing_length_tke_surf_scale]
value = 5.6101216504240545
type = "float"

[mixing_length_diss_coeff]
value = 0.3739697514813775
type = "float"

[diagnostic_covariance_coeff]
value = 1.4362168064049219
type = "float"

[entr_param_vec]
value = [-1.2633841186916668, -0.4599815783034937, -0.46293146485015296, 1.4203614863252911, 0.5642481281364011, 0.32604896101664416, -0.09664796099945236, 0.7220191192213364, 0.16903223715665835, 3.2461705926260187, -1.028004360914299, 0.3402928311687101]
type = "float"

[EDMF_surface_area]
value = 0.0723478159897135
type = "float"

[mixing_length_eddy_viscosity_coefficient]
value = 0.05607209843375782
type = "float"

[turb_entr_param_vec]
value = [0.08116105272535512, 6497.824633456959]
type = "float"

[pressure_normalmode_drag_coeff]
value = 36.11459646731416
type = "float"

[mixing_length_Prandtl_number_0]
value = 0.8133326091843176
type = "float"

[entr_inv_tau]
value = 0.00018836212008341437
type = "float"

[mixing_length_static_stab_coeff]
value = 0.8242481923752288
type = "float"

[pressure_normalmode_buoy_coeff1]
value = 0.06277435215676228
type = "float"
