# toml/rcemipii_box.toml

[c_smag]
value = 1.0

[condensation_evaporation_timescale]
value = 50

[sublimation_deposition_timescale]
value = 50

[angular_velocity_planet_rotation]
value = 0

[idealized_ocean_albedo]
value = 0.07

[mean_sea_level_pressure]
value = 101480

[D_0_diffusion]
value = 5

[H_diffusion]
value = 800

[SST_mean]
value = 300

[SST_delta]
value = 3

[SST_wavelength]
value = 6e6