# toml/rcemipii_box.toml

[c_smag]
value = 4.0

[condensation_evaporation_timescale]
value = 10

[sublimation_deposition_timescale]
value = 10

[angular_velocity_planet_rotation]
value = 0

[idealized_ocean_albedo]
value = 0.07

[mean_sea_level_pressure]
value = 101480

[D_0_diffusion]
value = 5

[H_diffusion]
value = 800