[zd_rayleigh]
value = 30000

[EDMF_surface_area]
value = 0.1

[EDMF_min_area]
value = 1.0e-5

[EDMF_max_area]
value = 0.7

[entr_inv_tau]
value = 0.0001

[entr_coeff]
value = 0.1

[min_area_limiter_scale]
value = 0

[detr_inv_tau]
value = 0.0001

[detr_coeff]
value = 0

[detr_buoy_coeff]
value = 0

[detr_vertdiv_coeff]
value = 0

[detr_massflux_vertdiv_coeff]
value = 1

[max_area_limiter_scale]
value = 0

[pressure_normalmode_drag_coeff]
value = 40.0

[tracer_vertical_diffusion_factor]
value = 0

[condensation_evaporation_timescale]
value = 50

[sublimation_deposition_timescale]
value = 50

[SST_mean]
value = 300

[SST_delta]
value = 0

[SST_wavelength]
value = 6e6
