rad: "allskywithclear"
rayleigh_sponge: true
orographic_gravity_wave: "raw_topo"
z_elem: 25
dt: "1secs"
surface_setup: "DefaultMoninObukhov"
t_end: "1mins"
non_orographic_gravity_wave: true
dz_bottom: 300.0
vert_diff: "true"
idealized_insolation: false
z_max: 45000.0
precip_model: "0M"
job_id: "flame_perf_gw"
moist: "equil"
toml: [toml/flame_perf_gw.toml]
