h_elem: 12
z_elem: 25
dt: 90secs
t_end: 61mins
dt_save_state_to_disk: "Inf"
log_progress: false
surface_setup: DefaultMoninObukhov
rad: allskywithclear
dt_rad: 1hours
dt_cloud_fraction: 1hours
turbconv: diagnostic_edmfx
prognostic_tke: true
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
microphysics_model: "0M"
toml: [toml/diagnostic_edmfx.toml]
