h_elem: 12
z_elem: 25
dt: 10secs
t_end: 31mins
dt_save_state_to_disk: "Inf"
log_progress: false
approximate_linear_solve_iters: 1
implicit_sgs_advection: true
implicit_sgs_entr_detr: true
implicit_sgs_nh_pressure: true
implicit_sgs_vertdiff: true
implicit_sgs_mass_flux: true
use_auto_jacobian: true
update_jacobian_every: stage
ode_algo: "ARS222"
debug_jacobian: true
moist: equil
surface_setup: DefaultMoninObukhov
rad: allskywithclear
dt_rad: 1hours
dt_cloud_fraction: 1hours
turbconv: prognostic_edmfx
max_newton_iters_ode: 3
prognostic_tke: true
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_vertical_diffusion: true
edmfx_filter: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
precip_model: 0M
toml: [toml/prognostic_edmfx.toml]
