h_elem: 12
z_elem: 25
dt: 10secs
t_end: 61mins
dt_save_state_to_disk: "Inf"
log_progress: false
implicit_sgs_advection: true
implicit_sgs_entr_detr: true
implicit_sgs_nh_pressure: true
implicit_sgs_vertdiff: true
implicit_sgs_mass_flux: true
surface_setup: DefaultMoninObukhov
rad: allskywithclear
dt_rad: 1hours
dt_cloud_fraction: 1hours
turbconv: prognostic_edmfx
max_newton_iters_ode: 3
prognostic_tke: true
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_vertical_diffusion: true
edmfx_filter: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
microphysics_model: "0M"
toml: [toml/prognostic_edmfx.toml]
