apply_limiter: true
h_elem: 12
z_elem: 25
dt: "1secs"
dt_rad: "1secs"
dt_cloud_fraction: "1secs"
t_end: "10secs"
dt_save_to_sol: "Inf"
dt_save_state_to_disk: "1secs"
implicit_diffusion: true
approximate_linear_solve_iters: 2
max_newton_iters_ode: 2
log_progress: false
moist: "equil"
surface_setup: "DefaultMoninObukhov"
rad: "allskywithclear"
vert_diff: true
precip_model: "0M"
