apply_sem_quasimonotone_limiter: true
h_elem: 12
z_elem: 25
rayleigh_sponge: false
viscous_sponge: false
dt: "1secs"
dt_rad: "1secs"
dt_cloud_fraction: "1secs"
t_end: "10secs"
dt_save_state_to_disk: "1secs"
log_progress: false
surface_setup: "DefaultMoninObukhov"
rad: "allskywithclear"
vert_diff: true
microphysics_model: "0M"
