h_elem: 12
z_elem: 25
rayleigh_sponge: false
viscous_sponge: false
dt: "1secs"
t_end: "10secs"
log_progress: false
surface_setup: "DefaultMoninObukhov"
rad: "allskywithclear"
vert_diff: true
microphysics_model: "0M"
perf_summary: true
