apply_limiter: true
h_elem: 12
z_elem: 25
dt: "1secs"
t_end: "10secs"
log_progress: false
implicit_diffusion: true
approximate_linear_solve_iters: 2
moist: "equil"
surface_setup: "DefaultMoninObukhov"
rad: "allskywithclear"
vert_diff: true
precip_model: "0M"
orographic_gravity_wave: "raw_topo"
non_orographic_gravity_wave: true
toml:
  - "toml/flame_perf_gw.toml"
