moist: "equil"
apply_limiter: true
z_elem: 25
dt: "1secs"
surface_setup: "DefaultExchangeCoefficients"
t_end: "10secs"
vert_diff: "true"
approximate_linear_solve_iters: 2
h_elem: 12
forcing: "held_suarez"
precip_model: "1M"
dt_save_to_sol: "Inf"
rad: "allskywithclear"
log_progress: false
implicit_diffusion: false
