apply_limiter: true
surface_setup: "DefaultExchangeCoefficients"
implicit_diffusion: true
approximate_linear_solve_iters: 2
h_elem: 12
forcing: "held_suarez"
dt_save_to_sol: "Inf"
rad: "allskywithclear"
log_progress: false
vert_diff: "FriersonDiffusion"
pproximate_linear_solve_iters: 2
use_krylov_method: true
use_dynamic_krylov_rtol: false
krylov_rtol: 0.99
precip_model: "0M"
z_elem: 20
dz_bottom: 100
dt_save_state_to_disk: "12hours"
initial_condition: "MoistBaroclinicWave"
dt: "40secs"
t_end: "12hours"
moist: "equil"
