diagnostics:
  - reduction_time: "average"
    short_name: "ua"
    period: "1secs"
  - reduction_time: "max"
    short_name: "va"
    period: "1secs"
  - reduction_time: "max"
    short_name: "ta"
    period: "1secs"
job_id: "flame_perf_diagnostics"
