FLOAT_TYPE: "Float32"
dt_save_state_to_disk: "5days"
t_end: "5days"
moist: "equil"
precip_model: "0M"
surface_setup: "DefaultMoninObukhov"
vert_diff: "DecayWithHeightDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
max_newton_iters_ode: 2
rad: "clearsky"
insolation: "timevarying"
dt_rad: "1hours"
prognostic_surface: "PrognosticSurfaceTemperature"
check_conservation: true
