constant_horizontal_diffusion: true
viscous_sponge: false
dt: "360secs"
t_end: "1days"
dt_save_state_to_disk: "24hours"
vert_diff: "DecayWithHeightDiffusion"
moist: "nonequil"
precip_model: "1M"
rad: "allskywithclear"
aerosol_radiation: true
prescribe_clouds_in_radiation: true
radiation_reset_rng_seed: true
insolation: "timevarying"
non_orographic_gravity_wave: true
orographic_gravity_wave: "gfdl_restart"
surface_setup: "DefaultMoninObukhov"
prescribe_ozone: true
reproducibility_test: true
prescribed_aerosols: ["SO4", "CB1", "OC1", "DST01", "SSLT01"]
toml: [toml/sphere_aquaplanet_1M.toml]
diagnostics:
  - short_name: [edt, evu, mmrso4, mmrbcpo, mmrocpo, mmrdust, mmrss, loadss, o3, od550aer, odsc550aer]
    reduction_time: average
    period: 1days
  - short_name: [reffclw, reffcli]
    period: 6hours
