dt_save_state_to_disk: "1days"
rayleigh_sponge: true
topo_smoothing: true
initial_condition: "MoistBaroclinicWave"
t_end: "450secs"
microphysics_model: "0M"
topography: "Earth"
apply_sem_quasimonotone_limiter: true
