FLOAT_TYPE: "Float64"
initial_condition: "MoistBaroclinicWave"
t_end: "5days"
microphysics_model: "0M"
disable_surface_flux_tendency: true
use_auto_jacobian: true
update_jacobian_every: dt
debug_jacobian: true
dt_save_state_to_disk: "5days"
check_conservation: true
diagnostics:
  - short_name: [massa, energya]
    period: 1days
    writer: dict
use_itime: true
