precip_model: "0M"
dt_save_state_to_disk: "10days"
reproducibility_test: true
initial_condition: "MoistBaroclinicWave"
dt: "450secs"
t_end: "2days"
moist: "equil"
disable_surface_flux_tendency: true
diagnostics:
  - short_name: [pfull, wa, va, rv, hus, ke]
    period: 1days
