precip_model: "0M"
dt_save_state_to_disk: "2days"
reproducibility_test: true
initial_condition: "MoistBaroclinicWave"
dt: "600secs"
t_end: "2days"
moist: "equil"
disable_surface_flux_tendency: true
diagnostics:
  - short_name: [pfull, wa, va, rv, hus, ke]
    period: 1days
    compute_every: 1steps
  - short_name: [pfull, wa, va, rv, hus, ke]
    period: 1days
    reduction_time: average
    pressure_coordinates: true
    compute_every: 1hours
use_sgs_quadrature: true
quadrature_order: 3
