topography: "DCMIP200"
dt_save_state_to_disk: "6days"
rayleigh_sponge: true
topo_smoothing: true
initial_condition: "DryBaroclinicWave"
t_end: "4days"
dt: "200secs"
hyperdiff: Hyperdiffusion
vorticity_hyperdiffusion_coefficient: 1.5
hyperdiffusion_prandtl_number: 1.0
divergence_damping_factor: 1.0
disable_surface_flux_tendency: true
netcdf_output_at_levels: false
diagnostics:
  - short_name: [pfull, wa, va, rv]
    period: 1days
