microphysics_model: "0M"
dt_save_state_to_disk: "2days"
reproducibility_test: true
initial_condition: "MoistBaroclinicWave"
dt: "450secs"
t_end: "6days"
disable_surface_flux_tendency: true
diagnostics:
  - short_name: [pfull, wa, va, rv, hus, ke]
    period: 1days
    compute_every: 1steps
  - short_name: [pfull, wa, va, rv, hus, ke]
    period: 1days
    reduction_time: average
    pressure_coordinates: true
    compute_every: 1hours
