edmf_coriolis: "Bomex"
initial_condition: "Bomex"
x_max: 10000.0
hyperdiff: "false"
z_elem: 60
dt: "0.5secs"
surface_setup: "Bomex"
perturb_initstate: false
t_end: "600secs"
y_max: 10000.0
z_stretch: false
vert_diff: "true"
config: "box"
subsidence: "Bomex"
z_max: 3000.0
ls_adv: "Bomex"
job_id: "bomex_box_rhoe"
moist: "equil"
toml: toml/bomex_box_rhoe.toml
