config: "box"
FLOAT_TYPE: "Float64"
initial_condition: "ConstantBuoyancyFrequencyProfile"
topography: "Cosine3D"
mesh_warp_type: "Linear"
x_max: 100e3
y_max: 25e3
z_max: 21e3
x_elem: 100
y_elem: 25
z_elem: 100
dz_bottom: 10
dt: "0.5secs" # CFL is slightly lower than for 2D case
t_end: "10mins"
rayleigh_sponge: true
disable_surface_flux_tendency: true
toml: [toml/steady_state_test.toml]
check_steady_state: true
output_default_diagnostics: false
diagnostics:
  - short_name: [orog, ua, wa, uapredicted, wapredicted, uaerror, waerror]
    period: 1mins
