dt_save_state_to_disk: "400secs"
initial_condition: "IsothermalProfile"
t_end: "1secs"
config: "column"
hyperdiff: false
dt: "1secs"
disable_surface_flux_tendency: true
non_orographic_gravity_wave: true
dt_nogw: "1secs"
toml: [toml/nogw_single_column_test.toml]
z_max: 47000.0
z_elem: 47
z_stretch: false
FLOAT_TYPE: "Float64"
