job_id: diagnostic_edmfx_aquaplanet
surface_setup: DefaultExchangeCoefficients 
rad: gray
turbconv: diagnostic_edmfx 
prognostic_tke: true
edmfx_upwinding: first_order 
edmfx_entr_model: "Generalized" 
edmfx_detr_model: "Generalized" 
edmfx_nh_pressure: true 
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: equil 
precip_model: 0M
override_Ï„_precip: false
dt: 50secs 
t_end: 1hours 
dt_save_to_disk: 600secs
toml: [toml/diagnostic_edmfx_trmm_box.toml]
