job_id: diagnostic_edmfx_dycoms_rf01_box
initial_condition: DYCOMS_RF01 
subsidence: DYCOMS 
edmf_coriolis: DYCOMS_RF01 
rad: DYCOMS_RF01 
surface_setup: DYCOMS_RF01
turbconv: diagnostic_edmfx 
prognostic_tke: true
edmfx_upwinding: first_order 
edmfx_entr_model: "Generalized" 
edmfx_detr_model: "Generalized" 
edmfx_nh_pressure: true 
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: equil
config: box 
hyperdiff: "true" 
kappa_4: 1e12
x_max: 1e5 
y_max: 1e5 
x_elem: 2 
y_elem: 2 
z_elem: 30 
z_max: 1500 
z_stretch: false
dt: 6secs 
t_end: 4hours 
dt_save_to_disk: 2mins
toml: [toml/diagnostic_edmfx_box.toml]
