job_id: diagnostic_edmfx_dycoms_rf01_box
initial_condition: DYCOMS_RF01 
subsidence: DYCOMS 
edmf_coriolis: DYCOMS_RF01 
rad: DYCOMS_RF01 
surface_setup: DYCOMS_RF01
turbconv: diagnostic_edmfx 
implicit_diffusion: true
approximate_linear_solve_iters: 2
prognostic_tke: true
edmfx_upwinding: first_order 
edmfx_entr_model: "Generalized" 
edmfx_detr_model: "Generalized" 
edmfx_nh_pressure: true 
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: equil
config: box 
hyperdiff: "true" 
x_max: 1e8 
y_max: 1e8 
x_elem: 2 
y_elem: 2 
z_elem: 30 
z_max: 1500 
z_stretch: false
dt: 100secs
t_end: 4hours 
dt_save_state_to_disk: 10mins
toml: [toml/diagnostic_edmfx_box.toml]
