job_id: diagnostic_edmfx_rico_box
initial_condition: Rico
subsidence: Rico
ls_adv: Rico
surface_setup: Rico
turbconv: diagnostic_edmfx
implicit_diffusion: true
approximate_linear_solve_iters: 2
prognostic_tke: true
edmfx_upwinding: first_order
edmfx_entr_model: "Generalized" 
edmfx_detr_model: "Generalized" 
edmfx_nh_pressure: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: equil
precip_model: "0M"
config: box
hyperdiff: "true"
kappa_4_vorticity: 1e21
kappa_4_tracer: 1e21
x_max: 1e8
y_max: 1e8
x_elem: 2
y_elem: 2
z_elem: 100
z_max: 4e3
z_stretch: false
dt: 100secs
t_end: 8hours
dt_save_to_disk: 10mins
toml: [toml/diagnostic_edmfx_trmm_box.toml]
