initial_condition: Rico
subsidence: Rico
ls_adv: Rico
surface_setup: Rico
turbconv: diagnostic_edmfx
implicit_diffusion: true
approximate_linear_solve_iters: 2
prognostic_tke: true
edmfx_upwinding: first_order
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
moist: equil
cloud_model: "quadrature_sgs"
precip_model: "0M"
call_cloud_diagnostics_per_stage: true
config: box
x_max: 1e8
y_max: 1e8
x_elem: 2
y_elem: 2
z_elem: 100
z_max: 4e3
z_stretch: false
dt: 100secs
t_end: 8hours
dt_save_state_to_disk: 10mins
toml: [toml/diagnostic_edmfx.toml]
netcdf_interpolation_num_points: [8, 8, 100]
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, pr]
    period: 10mins
  - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup, clwup, cliup, waen, tke, lmix]
    period: 10mins
ode_algo: ARS343
