dt: 120secs
surface_setup: DefaultMoninObukhov
rad: clearsky
turbconv: diagnostic_edmfx
prognostic_tke: true
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_sgsflux_upwinding: "vanleer_limiter"
edmfx_tracer_upwinding: "vanleer_limiter"
initial_condition: "AMIPFromERA5"
microphysics_model: "0M"
t_end: 12hours
toml: [toml/diagnostic_edmfx_0M.toml]
use_itime: true
