dt: 120secs
viscous_sponge: false
surface_setup: DefaultMoninObukhov
rad: clearsky
turbconv: diagnostic_edmfx
prognostic_tke: true
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
microphysics_model: "0M"
t_end: 3hours
reproducibility_test: true
toml: [toml/diagnostic_edmfx_0M.toml]
