config: column 
turbconv: edmf 
debugging_tc: true
FLOAT_TYPE: Float64 
hyperdiff: "false" 
turbconv_case: Nieuwstadt 
surface_setup: Nieuwstadt
z_elem: 200 
z_stretch: false 
z_max: 3750
t_end: 8hours 
dt_save_to_sol: 5mins 
dt_save_to_disk: 5mins
moist: equil
imex_edmf_turbconv: true
imex_edmf_gm: true
use_krylov_method: true
reference_job_id: edmf_nieuwstadt
job_id: edmf_nieuwstadt_jfnk_imex
dt: 50secs
