dt_save_to_disk: "5mins"
hyperdiff: "false"
z_elem: 150
dt: "50secs"
imex_edmf_gm: true
surface_setup: "Soares"
debugging_tc: true
turbconv_case: "Soares"
t_end: "8hours"
turbconv: "edmf"
z_stretch: false
imex_edmf_turbconv: true
config: "column"
use_krylov_method: true
FLOAT_TYPE: "Float64"
z_max: 3750.0
reference_job_id: "edmf_soares"
dt_save_to_sol: "5mins"
job_id: "edmf_soares_jfnk_imex"
moist: "equil"
