dt_save_to_disk: "100secs"
initial_condition: "MoistAdiabaticProfileEDMFX"
x_max: 10000.0
hyperdiff: "true"
z_elem: 45
dt: "10secs"
t_end: "1000secs"
y_max: 10000.0
y_elem: 2
turbconv: "edmfx"
x_elem: 2
dz_bottom: 30.0
ode_algo: "SSP33ShuOsher"
config: "box"
advection_test: true
kappa_4: 1.0e8
job_id: "edmfx_adv_test_box"
moist: "equil"
