edmf_coriolis: "LifeCycleTan2018"
dt_save_to_disk: "5mins"
hyperdiff: "false"
z_elem: 75
dt: "6secs"
debugging_tc: true
surface_setup: "LifeCycleTan2018"
turbconv_case: "LifeCycleTan2018"
t_end: "6hours"
turbconv: "edmf"
z_stretch: false
config: "column"
subsidence: "LifeCycleTan2018"
FLOAT_TYPE: "Float64"
z_max: 3000.0
apply_limiter: false
regression_test: true
ls_adv: "LifeCycleTan2018"
dt_save_to_sol: "5mins"
job_id: "edmf_life_cycle_tan2018"
moist: "equil"
