edmf_coriolis: "Bomex"
dt_save_to_disk: "60secs"
initial_condition: "Bomex"
x_max: 100000.0
hyperdiff: "true"
z_elem: 60
dt: "1secs"
edmfx_upwinding: first_order
surface_setup: "Bomex"
perturb_initstate: false
edmfx_entr_model: "ConstantCoefficient" 
edmfx_detr_model: "ConstantCoefficient" 
t_end: "10800secs"
y_max: 100000.0
y_elem: 2
turbconv: "edmfx"
z_stretch: false
vert_diff: "true"
x_elem: 2
config: "box"
subsidence: "Bomex"
kappa_4: 1.0e12
z_max: 3000.0
ls_adv: "Bomex"
job_id: "edmfx_bomex_box_v1"
moist: "equil"
toml: [toml/edmfx_bomex_box_v1.toml]
