config: column 
turbconv: edmf 
debugging_tc: true 
regression_test: true
FLOAT_TYPE: Float64 
hyperdiff: "false" 
turbconv_case: Nieuwstadt 
surface_setup: Nieuwstadt
z_elem: 200 
z_stretch: false 
z_max: 3750
t_end: 8hours
dt_save_to_sol: 5mins 
dt_save_to_disk: 5mins
moist: equil
job_id: edmf_nieuwstadt
dt: 0.5secs
