dt_save_to_disk: "8mins"
hyperdiff: "false"
z_elem: 100
dt: "0.75secs"
debugging_tc: true
surface_setup: "Rico"
turbconv_case: "Rico"
t_end: "24hours"
turbconv: "edmf"
z_stretch: false
config: "column"
subsidence: "Rico"
FLOAT_TYPE: "Float64"
z_max: 4000.0
precip_model: "1M"
regression_test: true
ls_adv: "Rico"
dt_save_to_sol: "5mins"
job_id: "edmf_rico"
moist: "equil"
