edmf_coriolis: "Bomex"
dt_save_to_disk: "5mins"
hyperdiff: "false"
z_elem: 60
dt: "30secs"
imex_edmf_gm: true
surface_setup: "Bomex"
debugging_tc: true
turbconv_case: "Bomex"
t_end: "6hours"
turbconv: "edmf"
z_stretch: false
imex_edmf_turbconv: true
config: "column"
subsidence: "Bomex"
use_krylov_method: true
FLOAT_TYPE: "Float64"
z_max: 3000.0
apply_limiter: false
reference_job_id: "edmf_bomex"
ls_adv: "Bomex"
dt_save_to_sol: "5mins"
job_id: "edmf_bomex_jfnk_imex"
moist: "equil"
