config: column 
turbconv: edmf 
debugging_tc: true 
regression_test: true
FLOAT_TYPE: Float64 
hyperdiff: "false" 
turbconv_case: GABLS 
edmf_coriolis: GABLS 
surface_setup: GABLS
z_elem: 8 
z_stretch: false 
z_max: 400
t_end: 9hours 
dt_save_to_sol: 5mins 
dt_save_to_disk: 5mins
moist: equil
imex_edmf_turbconv: true
imex_edmf_gm: true
use_krylov_method: true
job_id: edmf_gabls_jfnk_imex
dt: 600secs
