edmf_coriolis: "Bomex"
dt_save_to_disk: "60secs"
initial_condition: "Bomex"
x_max: 100000.0
hyperdiff: "true"
z_elem: 60
dt: "1secs"
edmfx_upwinding: first_order
surface_setup: "Bomex"
perturb_initstate: false
edmfx_entr_detr: true
t_end: "10800secs"
C_E: 0.044
y_max: 100000.0
y_elem: 2
turbconv: "edmfx"
z_stretch: false
vert_diff: "true"
x_elem: 2
detr_coeff: 0.01
config: "box"
subsidence: "Bomex"
kappa_4: 1.0e12
z_max: 3000.0
apply_limiter: false
ls_adv: "Bomex"
job_id: "edmfx_bomex_box_v2"
moist: "equil"
