edmf_coriolis: "DYCOMS_RF01"
moist: "equil"
dt_save_to_disk: "2mins"
hyperdiff: "false"
z_elem: 30
dt: "6secs"
debugging_tc: true
surface_setup: "DYCOMS_RF01"
turbconv_case: "DYCOMS_RF01"
t_end: "4hours"
turbconv: "edmf"
z_stretch: false
config: "column"
subsidence: "DYCOMS"
FLOAT_TYPE: "Float64"
z_max: 1500.0
apply_limiter: false
regression_test: true
dt_save_to_sol: "5mins"
job_id: "edmf_dycoms_rf01"
rad: "DYCOMS_RF01"
