z_max: 55000.0
implicit_diffusion: false
approximate_linear_solve_iters: 1
dt_save_state_to_disk: "1days"
t_end: "1days"
vert_diff: true
forcing: "held_suarez"
microphysics_model: "0M"
reproducibility_test: true
toml: [toml/sphere_held_suarez.toml]
