dt_save_state_to_disk: "3600secs"
initial_condition: "DryDensityCurrentProfile"
x_max: 51200.0
z_elem: 90
dt: "0.3secs"
t_end: "900.0secs"
discrete_hydrostatic_balance: true
z_stretch: false
x_elem: 80
config: "plane"
kappa_4_vorticity: 1.0e7
kappa_4_tracer: 1.0e7
z_max: 6400.0
job_id: "plane_density_current_test"
diagnostics:
  - short_name: thetaa
    period: 900secs
