dt_save_to_disk: "3600secs"
rayleigh_sponge: true
initial_condition: "AgnesiHProfile"
x_max: 240000.0
z_elem: 45
dt: "1.5secs"
t_end: "14400.0secs"
dz_top: 1000.0
x_elem: 80
dz_bottom: 200.0
use_reference_state: false
config: "plane"
kappa_4: 1.0e6
alpha_rayleigh_w: 0.1
z_max: 25000.0
topography: "Agnesi"
alpha_rayleigh_uh: 0.0
job_id: "plane_agnesi_mountain_test_stretched"
