dt_save_to_disk: "3600secs"
rayleigh_sponge: true
initial_condition: "AgnesiHProfile"
x_max: 240000.0
z_elem: 90
dt: "1.5secs"
t_end: "14400.0secs"
z_stretch: false
x_elem: 80
use_reference_state: false
config: "plane"
kappa_4: 1.0e6
z_max: 25000.0
topography: "Agnesi"
job_id: "plane_agnesi_mountain_test_uniform"
toml: toml/plane_agnesi_mountain_test_uniform.toml
