dt_save_state_to_disk: "3600secs"
initial_condition: "DryDensityCurrentProfile"
x_max: 51200.0
z_elem: 90
dt: "0.3secs"
t_end: "400.0secs"
amd_les: true
z_stretch: false
x_elem: 80
config: "plane"
z_max: 6400.0
disable_surface_flux_tendency: true
output_default_diagnostics: false
diagnostics:
  - short_name: thetaa
    period: 900secs
