dt_save_to_disk: "3600secs"
rayleigh_sponge: true
initial_condition: "ScharProfile"
x_max: 120000.0
z_elem: 45
dt: "0.5secs"
t_end: "14400.0secs"
z_stretch: false
x_elem: 100
use_reference_state: false
ode_algo: "SSP33ShuOsher"
config: "plane"
kappa_4: 5.0e7
z_max: 25000.0
topography: "Schar"
job_id: "plane_schar_mountain_test_uniform"
toml: [toml/plane_schar_mountain_test_uniform.toml]
netcdf_interpolate_z_over_msl: true
diagnostics:
  - short_name: wa
    period: 4hours
