initial_condition: DYCOMS_RF01
subsidence: DYCOMS
scm_coriolis: DYCOMS_RF01
rad: DYCOMS
surface_setup: DYCOMS_RF01
turbconv: prognostic_edmfx
implicit_diffusion: true
implicit_sgs_advection: false
approximate_linear_solve_iters: 2
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: true
edmfx_vertical_diffusion: true
edmfx_filter: true
prognostic_tke: true
moist: equil
config: column
hyperdiff: "false"
z_max: 1500
x_elem: 2
y_elem: 2
z_elem: 30
z_stretch: false
dt: 10secs
t_end: 4hours
dt_save_state_to_disk: 10mins
toml: [toml/prognostic_edmfx.toml]
netcdf_interpolation_num_points: [2, 2, 30]
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, pr]
    period: 10mins
  - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup, clwup, cliup, waen, taen, thetaaen, haen, husen, huren, clwen, clien, tke]
    period: 10mins
  - short_name: [entr, detr, lmix, bgrad, strain, edt, evu]
    period: 10mins
ode_algo: "ARS222"
