surface_setup: DefaultMoninObukhov
surface_temperature: RCEMIPII
rad: allskywithclear
turbconv: diagnostic_edmfx
insolation: rcemipii
prognostic_tke: true
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
rayleigh_sponge: true
microphysics_model: "0M"
t_end: 12hours
dt_save_state_to_disk: 12hours
toml: [toml/rcemipii_diagnostic_edmfx_0M.toml]
