z_max: 60000.0
z_elem: 31
dz_bottom: 50.0
rad: "allskywithclear"
dt_save_state_to_disk: "1days"
rayleigh_sponge: true
orographic_gravity_wave: "raw_topo"
dt: "400secs"
surface_setup: "DefaultMoninObukhov"
t_end: "15hours"
non_orographic_gravity_wave: true
vert_diff: true
insolation: "timevarying"
precip_model: "0M"
cloud_model: "grid_scale"
surface_temperature: "ZonallyAsymmetric"
moist: "equil"
albedo_model: "RegressionFunctionAlbedo"
reproducibility_test: true
aerosol_radiation: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "DST02", "DST03", "DST04", "OC1", "OC2", "SO4"]
toml: [toml/sphere_aquaplanet.toml]
