dt_save_to_disk: "5days"
initial_condition: "MoistBaroclinicWave"
max_newton_iters_ode: 4
dt: "400secs"
tracer_upwinding: zalesak
t_end: "5days"
ode_algo: "SSP333"
energy_upwinding: zalesak
precip_model: "0M"
regression_test: true
job_id: "sphere_zalesak_upwind_tracer_energy_ssp_baroclinic_wave_rhoe_equilmoist"
moist: "equil"
apply_limiter: true
