job_id: "sphere_baroclinic_wave_rhoe_equilmoist_edmf" 
vert_diff: "true" 
surface_setup: "DefaultExchangeCoefficients" 
moist: "dry" 
dt: "1secs" 
t_end: "20secs" 
FLOAT_TYPE: "Float64" 
turbconv: "edmf" 
config: "sphere" 
z_stretch: false 
post_process: false 
apply_limiter: false 
dt_save_to_sol: "10secs" 
dt_save_to_disk: "10secs"