z_max: 60000.0
z_elem: 31
dz_bottom: 50.0
dt: "400secs"
t_end: "18hours"
dt_save_state_to_disk: "18hours"
vert_diff: "DecayWithHeightDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
cloud_model: "grid_scale"
moist: "nonequil"
precip_model: "1M"
rad: "allskywithclear"
insolation: "timevarying"
rayleigh_sponge: true
surface_setup: "DefaultMoninObukhov"
toml: [toml/sphere_aquaplanet.toml]
