topography: "DCMIP200"
dt_save_state_to_disk: "6days"
rayleigh_sponge: true
topo_smoothing: true
initial_condition: "DryBaroclinicWave"
t_end: "6days"
dt: "200secs"
netcdf_output_at_levels: false
diagnostics:
  - short_name: [pfull, wa, va, rv]
    period: 1days
