initial_condition: "MoistBaroclinicWave"
dt: "400secs"
t_end: "10days"
moist: "equil"
surface_setup: DefaultMoninObukhov
prognostic_surface: "PrognosticSurfaceTemperature"
rad: "clearsky"
precip_model: "0M"
vert_diff: true
dt_save_state_to_disk: "5days"
check_conservation: true
