dt_save_to_disk: "4days"
rayleigh_sponge: true
dt: "450secs"
z_elem: 25
t_end: "4days"
dz_bottom: 300.0
vert_diff: "true"
forcing: "held_suarez"
z_max: 45000.0
precip_model: "0M"
regression_test: true
viscous_sponge: true
job_id: "sphere_held_suarez_rhoe_equilmoist_hightop_sponge"
moist: "equil"
toml: [toml/sphere_held_suarez_rhoe_equilmoist_hightop_sponge.toml]
netcdf_interpolate_z_over_msl: true
