precip_model: "0M"
dt_save_state_to_disk: "2days"
regression_test: true
initial_condition: "MoistBaroclinicWave"
dt: "450secs"
job_id: "sphere_baroclinic_wave_rhoe_equilmoist"
moist: "equil"
diagnostics:
  - short_name: [pfull, wa, va, rv, hus]
    period: 1days
