precip_model: "0M"
dt_save_state_to_disk: "2days"
reproducibility_test: false
initial_condition: "MoistBaroclinicWave"
dt: "450secs"
t_end: "10days"
moist: "equil"
diagnostics:
  - short_name: [pfull, wa, va, rv, hus, ke]
    period: 1days
