topography: "DCMIP200"
dt_save_to_disk: "3days"
rayleigh_sponge: true
topo_smoothing: true
use_reference_state: false
t_end: "3days"
forcing: "held_suarez"
dt: "200secs"
viscous_sponge: true
job_id: "sphere_held_suarez_rhoe_topography_dcmip"
netcdf_interpolate_z_over_msl: true
