precip_model: "0M"
dt_save_to_disk: "2days"
regression_test: true
initial_condition: "MoistBaroclinicWave"
dt: "450secs"
job_id: "sphere_baroclinic_wave_rhoe_equilmoist"
moist: "equil"
diagnostics:
  - short_name: pfull
    period: 1days
  - short_name: wa
    period: 1days
  - short_name: va
    period: 1days
  - short_name: rv
    period: 1days
  - short_name: hus
    period: 1days
