dt_save_to_disk: "4days"
rayleigh_sponge: true
zd_rayleigh: 30000.0
zd_viscous: 30000.0
dt: "450secs"
z_elem: 25
t_end: "4days"
dz_bottom: 300.0
vert_diff: "true"
forcing: "held_suarez"
z_max: 45000.0
precip_model: "0M"
regression_test: true
alpha_rayleigh_uh: 0.0
viscous_sponge: true
job_id: "sphere_held_suarez_rhoe_equilmoist_hightop_sponge"
moist: "equil"
