dt_save_state_to_disk: "1days"
rayleigh_sponge: true
topo_smoothing: true
initial_condition: "MoistBaroclinicWave"
dt: "450secs"
t_end: "450secs"
precip_model: "0M"
topography: "Earth"
moist: "equil"
apply_limiter: true
