dt_save_to_disk: "3days"
rayleigh_sponge: true
zd_rayleigh: 30000.0
zd_viscous: 30000.0
dt: "300secs"
z_elem: 25
tracer_upwinding: first_order
t_end: "3days"
dz_bottom: 300.0
vert_diff: "true"
ode_algo: "SSP333"
forcing: "held_suarez"
energy_upwinding: first_order
z_max: 45000.0
precip_model: "0M"
viscous_sponge: true
job_id: "sphere_ssp_first_tracer_energy_upwind_held_suarez_rhoe_equilmoist_hightop_sponge"
moist: "equil"
apply_limiter: true
