topography: "DCMIP200"
dt_save_to_disk: "6days"
rayleigh_sponge: true
topo_smoothing: true
initial_condition: "DryBaroclinicWave"
t_end: "6days"
use_reference_state: false
dt: "200secs"
job_id: "sphere_baroclinic_wave_rhoe_topography_dcmip_rs"
