z_max: 60000.0
z_elem: 31
dz_bottom: 50.0
rayleigh_sponge: true
dt: "360secs"
t_end: "1days"
dt_save_state_to_disk: "24hours"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
approximate_linear_solve_iters: 2
moist: "nonequil"
precip_model: "1M"
rad: "allskywithclear"
aerosol_radiation: true
prescribe_clouds_in_radiation: true
radiation_reset_rng_seed: true
insolation: "timevarying"
non_orographic_gravity_wave: true
orographic_gravity_wave: "gfdl_restart"
surface_setup: "DefaultMoninObukhov"
prescribe_ozone: true
reproducibility_test: true
prescribed_aerosols: ["CB1", "CB2", "SO4"]
toml: [toml/sphere_aquaplanet.toml]
diagnostics:
  - short_name: [edt, evu, mmrso4, mmrbcpo, mmrbcpi, o3]
    reduction_time: average
    period: "1days"
