rad: "clearsky"
dt_save_to_disk: "10days"
rayleigh_sponge: true
z_elem: 50
dt: "150secs"
surface_setup: "DefaultMoninObukhov"
t_end: "300days"
dz_top: 3000.0
dz_bottom: 30.0
vert_diff: "true"
h_elem: 16
kappa_4: 1.0e16
FLOAT_TYPE: "Float32"
z_max: 45000.0
precip_model: "0M"
job_id: "longrun_aquaplanet_rhoe_equil_clearsky_highres_hightop_rayleigh35e3_ft32"
moist: "equil"
toml: [toml/longrun_aquaplanet_rhoe_equil_clearsky_highres_hightop_rayleigh35e3_ft32.toml]
