dz_bottom: 30.0
dt_save_state_to_disk: "10days"
h_elem: 16
initial_condition: "DryBaroclinicWave"
t_end: "100days"
z_elem: 45
dt: "400secs"
job_id: "longrun_bw_rhoe_highres"
diagnostics:
  - short_name: [pfull, wa, va, rv]
