t_end: "360days"
dt_save_state_to_disk: "30days"
check_conservation: true
prognostic_surface: "SlabOceanSST"
albedo_model: "RegressionFunctionAlbedo"
surface_setup: "DefaultMoninObukhov"
vert_diff: "DecayWithHeightDiffusion"
rad: "allskywithclear"
insolation: "timevarying"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
microphysics_model: "0M"
toml: [toml/longrun_aquaplanet.toml]
