FLOAT_TYPE: "Float32"
dt_save_to_disk: "10days"
dt: "150secs"
t_end: "300days"
h_elem: 16
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
rayleigh_sponge: true
kappa_4: 2.0e16
moist: "equil"
precip_model: "1M"
precip_upwinding: "first_order"
surface_setup: "DefaultMoninObukhov"
vert_diff: "true"
rad: "clearsky"
idealized_insolation: false
dt_rad: "1hours"
job_id: "longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation_1M"
toml: [toml/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky.toml]
