h_elem: 16
z_max: 60000.0
z_elem: 63
dz_bottom: 30.0
deep_atmosphere: false
rayleigh_sponge: true
viscous_sponge: true
implicit_diffusion: true
approximate_linear_solve_iters: 2
dt: "120secs"
t_end: "360days"
dt_save_state_to_disk: "10days"
moist: "nonequil"
rad: "allskywithclear"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
surface_setup: "DefaultMoninObukhov"
turbconv: "edonly_edmfx"
edmfx_sgs_diffusive_flux: true
precip_model: "1M"
toml: [toml/longrun_aquaplanet_1M.toml]
