dt_save_state_to_disk: "10days"
rayleigh_sponge: true
topo_smoothing: true
initial_condition: "MoistBaroclinicWave"
z_elem: 45
dt: "100secs"
t_end: "100days"
dz_bottom: 30.0
h_elem: 16
use_reference_state: false
precip_model: "0M"
topography: "Earth"
job_id: "longrun_bw_rhoe_equil_highres_topography_earth"
moist: "equil"
