t_end: "10days"
dt_save_state_to_disk: "10days"
moist: "equil"
rad: "allskywithclear"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
surface_setup: "DefaultMoninObukhov"
turbconv: "edonly_edmfx"
edmfx_sgs_diffusive_flux: true
precip_model: "0M"
toml: [toml/longrun_aquaplanet.toml]
