h_elem: 16
z_max: 55000.0
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
rayleigh_sponge: true
implicit_diffusion: true
approximate_linear_solve_iters: 2
max_newton_iters_ode: 3
dt: "120secs"
t_end: "240days"
dt_save_state_to_disk: "30days"
moist: "equil"
rad: "allskywithclear"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
surface_setup: "DefaultMoninObukhov"
turbconv: "prognostic_edmfx"
zero_tendency: "subgrid_scale"
prognostic_tke: true
edmfx_upwinding: "first_order"
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: false
edmfx_filter: true
edmfx_sgs_mass_flux: false
edmfx_sgs_diffusive_flux: true
precip_model: "0M"
override_Ï„_precip: false
toml: [toml/longrun_aquaplanet_progedmf.toml]
