rad: "allskywithclear"
dt_save_to_disk: "10days"
rayleigh_sponge: true
dt_rad: "1hours"
z_elem: 45
dt: "150secs"
surface_setup: "DefaultMoninObukhov"
t_end: "100days"
dz_bottom: 30.0
vert_diff: "true"
h_elem: 16
kappa_4: 1.0e16
idealized_insolation: false
FLOAT_TYPE: "Float32"
precip_model: "0M"
job_id: "longrun_aquaplanet_rhoe_equil_highres_allsky_ft32"
moist: "equil"
