h_elem: 120
z_elem: 43
dz_bottom: 30.0
dt: "40secs" 
approximate_linear_solve_iters: 3
max_newton_iters_ode: 1
rayleigh_sponge: true
t_end: "15days"
initial_condition: "MoistBaroclinicWave"
moist: "nonequil"
precip_model: "1M"
dt_save_state_to_disk: "10days"
output_dir: "/glade/derecho/scratch/asridhar/moist_bw_1M/"
toml: [toml/longrun_baroclinic_wave.toml]
diagnostics:
  - short_name: [pfull, ua, va, ta, ts, wa, va, rv, ke, hus, clw, cli, pr, husra, hussn, ]
    reduction: inst
    period: 2days
  - short_name: [massa, energya, watera]
    period: 6hours
    writer: dict
