dt_save_to_disk: "10days"
rayleigh_sponge: true
topo_smoothing: true
z_elem: 45
dt: "100secs"
t_end: "400days"
dz_bottom: 30.0
vert_diff: "true"
h_elem: 16
use_reference_state: false
kappa_4: 3.0e16
forcing: "held_suarez"
precip_model: "0M"
topography: "Earth"
job_id: "longrun_hs_rhoe_equil_highres_topography_earth"
moist: "equil"
