dt_save_to_disk: "10days"
initial_condition: "MoistBaroclinicWave"
z_elem: 45
dt: "300secs"
t_end: "100days"
dz_bottom: 30.0
h_elem: 16
kappa_4: 1.0e16
apply_limiter: false
precip_model: "0M"
job_id: "longrun_bw_rhoe_equil_highres"
moist: "equil"
