h_elem: 16
z_max: 60000.0
z_elem: 63
dz_bottom: 30.0
rayleigh_sponge: true
viscous_sponge: true
implicit_diffusion: true
approximate_linear_solve_iters: 2
dt: "120secs"
t_end: "360days"
dt_save_state_to_disk: "30days"
check_conservation: true
moist: "equil"
prognostic_surface: "PrognosticSurfaceTemperature"
albedo_model: "RegressionFunctionAlbedo"
surface_setup: "DefaultMoninObukhov"
vert_diff: "FriersonDiffusion"
rad: "allskywithclear"
insolation: "timevarying"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
precip_model: "0M"
toml: [toml/longrun_aquaplanet.toml]
