t_end: "360days"
dt_save_state_to_disk: "10days"
moist: "nonequil"
rad: "allskywithclear"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
surface_setup: "DefaultMoninObukhov"
turbconv: "edonly_edmfx"
edmfx_sgs_diffusive_flux: true
precip_model: "1M"
use_sgs_quadrature: false
tracer_nonnegativity_method: "vertical_water_borrowing"

vertical_water_borrowing_species: ["œÅq_tot"]
toml: [toml/longrun_aquaplanet_1M.toml]
