implicit_sgs_advection: true
implicit_sgs_mass_flux: true
implicit_sgs_entr_detr: true
implicit_sgs_nh_pressure: true
implicit_sgs_vertdiff: true
max_newton_iters_ode: 3
ode_algo: "ARS222"
dt: "120secs"
t_end: "240days"
dt_save_state_to_disk: "30days"
moist: "equil"
rad: "allskywithclear"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
surface_setup: "DefaultMoninObukhov"
turbconv: "prognostic_edmfx"
prognostic_tke: true
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_vertical_diffusion: true
edmfx_filter: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
precip_model: "0M"
toml: [toml/longrun_aquaplanet_progedmf.toml]
