h_elem: 30
z_elem: 43
dz_bottom: 30.0
dt: "90secs"
t_end: "120days"
initial_condition: "DryBaroclinicWave"
dt_save_state_to_disk: "10days"
diagnostics:
  - short_name: [pfull, wa, va, rv, ke]
    period: 10days
