dt_save_to_disk: "10days"
dt: "150secs"
t_end: "300days"
h_elem: 16
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
kappa_4: 2.0e16
vert_diff: "true"
moist: "equil"
precip_model: "0M"
rayleigh_sponge: true
alpha_rayleigh_w: 10.0
zd_rayleigh: 35000.0
forcing: "held_suarez"
job_id: "longrun_hs_rhoe_equilmoist_nz63_0M_55km_rs35km"
