vert_diff: "true" 
surface_setup: "DefaultExchangeCoefficients" 
moist: "equil" 
rad: "gray" 
precip_model: "0M" 
dt: "450secs" 
t_end: "600days" 
fps: 30 
job_id: "longrun_aquaplanet_rhoe_equil_gray" 
dt_save_to_sol: "1days" 
dt_save_to_disk: "10days"
