rad: "clearsky"
dt_save_to_disk: "10days"
rayleigh_sponge: true
z_elem: 45
dt: "150secs"
surface_setup: "DefaultMoninObukhov"
fps: 30
t_end: "300days"
dz_bottom: 30.0
vert_diff: "true"
h_elem: 16
kappa_4: 1.0e16
FLOAT_TYPE: "Float64"
apply_limiter: false
precip_model: "0M"
alpha_rayleigh_uh: 0.0
dt_save_to_sol: "10days"
job_id: "longrun_aquaplanet_rhoe_equil_highres_clearsky_ft64"
moist: "equil"
