h_elem: 60
dt: "30secs"
t_end: "30days"
initial_condition: "MoistBaroclinicWave"
microphysics_model: "0M"
dt_save_state_to_disk: "10days"
disable_surface_flux_tendency: true
netcdf_interpolation_num_points: [360, 180, 2]
toml: [toml/longrun_baroclinic_wave.toml]
diagnostics:
  - short_name: [pfull, wa, va, rv, hus, ke]
    period: 10days
