implicit_diffusion: false
approximate_linear_solve_iters: 1
t_end: "360days"
microphysics_model: "0M"
vert_diff: true
forcing: "held_suarez"
dt_save_state_to_disk: "10days"
toml: [toml/longrun_held_suarez.toml]
