dt_save_to_disk: "10days"
initial_condition: "MoistBaroclinicWave"
max_newton_iters_ode: 3
z_elem: 45
dt: "200secs"
tracer_upwinding: first_order
t_end: "100days"
dz_bottom: 30.0
h_elem: 16
ode_algo: "SSP333"
kappa_4: 1.0e16
energy_upwinding: first_order
precip_model: "0M"
job_id: "longrun_ssp_first_tracer_energy_upwind_bw_rhoe_equil_highres"
moist: "equil"
apply_limiter: true
