[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
ArtifactWrappers = "a14bc488-3040-4b00-9dc1-f6467924858a"
AtmosphericProfilesLibrary = "86bc3604-9858-485a-bdbe-831ec50de11d"
CLIMAParameters = "6eacf6c3-8458-43b9-ae03-caf5306d3d53"
ClimaCore = "d414da3d-4745-48bb-8d80-42e94e092884"
CloudMicrophysics = "6a9e3e04-43cd-43ba-94b9-e8782df3c71b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LambertW = "984bce1d-4616-540c-a9ee-88d1112d94c9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
OperatorFlux = "47cfafe2-3833-4da3-8183-ce14c2b92cbd"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PoissonRandom = "e409e4f3-bfea-5376-8464-e040bb5c01ab"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReportMetrics = "c1654acf-408b-4272-96ce-66c258df8a6c"
RootSolvers = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
SurfaceFluxes = "49b00bb7-8bd4-4f2b-b78c-51cd0450215f"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Thermodynamics = "b60c26fb-14c3-4610-9d3e-2d17fe7ff00c"
TurbulenceConvection = "8e072fc4-01f8-44fb-b9dc-f9336c367e6b"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
ArgParse = "1.1"
ArtifactWrappers = "0.1"
AtmosphericProfilesLibrary = "0.1"
CLIMAParameters = "0.4"
ClimaCore = "0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9"
CloudMicrophysics = "0.3"
Dierckx = "0.5"
Distributions = "0.25"
DocStringExtensions = "0.8"
FastGaussQuadrature = "0.4"
Flux = "0.12"
Glob = "1.3"
JSON = "0.21"
LambertW = "0.4"
NCDatasets = "0.11, 0.12"
OperatorFlux = "0.1"
OrderedCollections = "1.4"
OrdinaryDiffEq = "5.63, 6"
PoissonRandom = "0.4"
PrettyTables = "1.2"
RootSolvers = "0.2, 0.3"
SciMLBase = "1"
StaticArrays = "1.2"
StatsBase = "0.33"
StochasticDiffEq = "6.41"
SurfaceFluxes = "0.2"
TerminalLoggers = "0.1"
Thermodynamics = "0.5, 0.6"
UnPack = "1.0"
julia = "1.5"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
