config: sphere
h_elem: 6 # 550 km
nh_poly: 3
z_elem: 31
z_max: 60000.0
dz_bottom: 50.0
dt: 400secs
ode_algo: ARS343
hyperdiff: Hyperdiffusion
rayleigh_sponge: true
viscous_sponge: true
implicit_diffusion: true
approximate_linear_solve_iters: 2
max_newton_iters_ode: 1
