vert_diff: "DecayWithHeightDiffusion"
surface_setup: "DefaultExchangeCoefficients"
rad: "clearsky"
microphysics_model: "0M"
dt: "400secs"
t_end: "4days"
# Test HDF5 writer with MPI as well
diagnostics:
  - short_name: [pfull, wa, va, rv]
    period: 1days
    writer: h5
