dt_save_state_to_disk: "Inf"
output_default_diagnostics: false
h_elem: 42
microphysics_model: "0M"
rad: "allskywithclear"
insolation: "timevarying"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
vert_diff: "DecayWithHeightDiffusion"
surface_setup: "DefaultMoninObukhov"
t_end: "1days"
toml: [toml/longrun_aquaplanet.toml]
time_varying_trace_gases: ["O3"]
aerosol_radiation: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "DST02", "DST03", "DST04", "DST05", "OC1", "OC2", "SO4", "SSLT01", "SSLT02", "SSLT03", "SSLT04", "SSLT05"]
