dt: "60secs"
dt_save_state_to_disk: "Inf"
microphysics_model: "0M"
rad: "allskywithclear"
insolation: "timevarying"
dt_rad: "1hours"
dt_cloud_fraction: "1hours"
turbconv: "edonly_edmfx"
edmfx_sgs_diffusive_flux: true
surface_setup: "DefaultMoninObukhov"
t_end: "1hours"
check_nan_every: 1
toml: [toml/longrun_aquaplanet.toml]
time_varying_trace_gases: ["O3"]
aerosol_radiation: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "DST02", "DST03", "DST04", "DST05", "OC1", "OC2", "SO4", "SSLT01", "SSLT02", "SSLT03", "SSLT04", "SSLT05"]
start_date: "20160801"
initial_condition: "artifact\"DYAMOND_SUMMER_ICS_p98deg\"/DYAMOND_SUMMER_ICS_p98deg.nc"
topography: "Earth"
diagnostics:
  - short_name: [massa, energya]
    period: 1hours
    writer: dict

