implicit_diffusion: false
approximate_linear_solve_iters: 1
t_end: "1days"
dt_save_state_to_disk: "Inf"
output_default_diagnostics: false
vert_diff: true
microphysics_model: "0M"
forcing: "held_suarez"
toml: [toml/longrun_held_suarez.toml]
